version: '3.4'

services:
  openvpn:
    build:
      context: .
      network: host
    ports:
      - 1194:1194/udp
    env_file:
      - .env
    volumes:
      - ./dist:/etc/openvpn
    cap_add:
      - NET_ADMIN
